"""
Test Scaffold Generator (Tasks 4.5, 4.6)

Generates test scaffolds for verifying security findings.

Philosophy:
- Tier 1: MUST NEVER FAIL - always produces useful output
- Tier 2: Attempts smart resolution - ~30-40% compile rate
- Tier 3: Aspirational full tests - <10% success rate

This module generates test files that help auditors verify vulnerabilities.
It does NOT attempt to automatically exploit or verify findings.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Dict, List, Optional, Any

from alphaswarm_sol.enterprise.reports import Finding, Severity
from alphaswarm_sol.testing.detection import ProjectConfig, ProjectType
from alphaswarm_sol.testing.remappings import ImportResolver
from alphaswarm_sol.testing.pragma import suggest_test_pragma
from alphaswarm_sol.testing.tiers import TestTier


@dataclass
class TestScaffold:
    """
    Generated test scaffold.

    Attributes:
        finding_id: ID of the finding this tests
        tier: Generation tier (1, 2, or 3)
        content: Solidity test file content
        filename: Suggested filename
        compiled: Whether compilation was attempted/succeeded
        compilation_error: Error message if compilation failed
        confidence: Estimated likelihood this compiles (0.0 to 1.0)
    """

    finding_id: str
    tier: int
    content: str
    filename: str
    compiled: Optional[bool] = None
    compilation_error: Optional[str] = None
    confidence: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "finding_id": self.finding_id,
            "tier": self.tier,
            "filename": self.filename,
            "compiled": self.compiled,
            "compilation_error": self.compilation_error,
            "confidence": self.confidence,
            "content_length": len(self.content),
        }


# =============================================================================
# TIER 1 TEMPLATE - Always produces output
# =============================================================================

TIER1_TEMPLATE = '''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

// =============================================================================
// VKG TEST SCAFFOLD - TIER 1 (Template)
// Generated: {timestamp}
// Finding: {finding_id}
// =============================================================================
//
// This is a TEMPLATE that requires manual completion.
// Search for "TODO" to find sections that need your input.
//
// Tier 1 scaffolds are designed to NEVER FAIL - they always produce output
// but require manual work to become compilable and functional.
//
// =============================================================================

// TODO: Add correct import path for the target contract
// The contract is located at: {location}
// Common import patterns:
//   Foundry: import "../src/Contract.sol";
//   Hardhat: import "../contracts/Contract.sol";
// import "{{TARGET_CONTRACT_PATH}}";

// TODO: Add forge-std import (Foundry projects only)
// If using Foundry: forge install foundry-rs/forge-std
// import "forge-std/Test.sol";

/**
 * @title {test_contract_name}
 * @notice Test for vulnerability: {finding_title}
 * @dev Generated by VKG - requires manual completion
 */
contract {test_contract_name} /* is Test */ {{
    // =========================================================================
    // VULNERABILITY SUMMARY
    // =========================================================================
    // ID: {finding_id}
    // Severity: {severity}
    // Category: {category}
    // Location: {location}
    //
    // Description:
    // {description}
    //
    // Recommendation:
    // {recommendation}
    // =========================================================================

    // TODO: Declare the target contract instance
    // {target_contract_type} public target;

    // TODO: Declare any attacker contracts if needed
    // AttackerContract public attacker;

    function setUp() public {{
        // TODO: Deploy or connect to the target contract
        // Option 1: Deploy fresh instance
        // target = new {target_contract_type}();
        //
        // Option 2: Fork mainnet and use existing deployment
        // vm.createSelectFork("mainnet");
        // target = {target_contract_type}(0x...);

        // TODO: Set up initial state
        // - Fund accounts with ETH/tokens
        // - Set up roles/permissions
        // - Create any helper contracts
    }}

    function test_{finding_id_safe}_{category_safe}() public {{
        // =====================================================================
        // ATTACK SCENARIO
        // =====================================================================
{attack_steps}
        // =====================================================================

        // TODO: Step 1 - Set up preconditions
        // Record initial balances, state, etc.
        // uint256 initialBalance = target.balanceOf(address(this));

        // TODO: Step 2 - Execute attack
        // Call the vulnerable function
        // target.vulnerableFunction(...);

        // TODO: Step 3 - Verify vulnerability
        // Assert that the attack succeeded
        // assertGt(target.balanceOf(address(this)), initialBalance, "Attack should increase balance");

        // TODO: Remove this line after implementing the test
        revert("Test not implemented - see TODO comments above");
    }}
}}

// =============================================================================
// HELPER CONTRACTS (if needed)
// =============================================================================
//
// For reentrancy attacks, you may need an attacker contract:
//
// contract Attacker {{
//     {target_contract_type} public target;
//
//     constructor(address _target) {{
//         target = {target_contract_type}(_target);
//     }}
//
//     receive() external payable {{
//         // TODO: Implement reentrancy callback
//         // if (address(target).balance > 0) {{
//         //     target.withdraw();
//         // }}
//     }}
//
//     function attack() external payable {{
//         // TODO: Implement attack entry point
//     }}
// }}
//
// =============================================================================
'''


def generate_tier1_scaffold(finding: Finding) -> TestScaffold:
    """
    Generate Tier 1 test scaffold.

    MUST NOT FAIL. Always produces output.

    Tier 1 provides:
    - Test file structure with valid Solidity syntax
    - Vulnerability description in comments
    - Attack vector explanation for the category
    - TODO markers for manual completion
    - Helper contract templates

    Args:
        finding: The finding to generate test for

    Returns:
        TestScaffold with template content
    """
    try:
        # Safe extraction - handle missing/empty data gracefully
        finding_id = finding.id or "UNKNOWN"
        finding_id_safe = _make_safe_identifier(finding_id)

        # Extract category from finding
        # The Finding class doesn't have a category field, extract from location or title
        category = _extract_category(finding)
        category_safe = _make_safe_identifier(category)

        test_contract_name = f"Test_{finding_id_safe}_{category_safe}"

        # Extract location info
        location = finding.location or "unknown"
        target_contract_type = _extract_contract_name(location)

        # Build attack steps from category
        attack_steps = _generate_attack_steps(category)

        # Generate content
        content = TIER1_TEMPLATE.format(
            timestamp=datetime.now().isoformat(),
            finding_id=finding_id,
            finding_id_safe=finding_id_safe,
            finding_title=finding.title or "Unknown Vulnerability",
            severity=finding.severity.value if finding.severity else "unknown",
            category=category,
            category_safe=category_safe,
            location=location,
            description=_indent_text(finding.description or "No description provided"),
            recommendation=_indent_text(finding.recommendation or "No recommendation provided"),
            test_contract_name=test_contract_name,
            target_contract_type=target_contract_type,
            attack_steps=attack_steps,
        )

        # Generate filename
        filename = f"{test_contract_name}.t.sol"

        return TestScaffold(
            finding_id=finding_id,
            tier=1,
            content=content,
            filename=filename,
            confidence=1.0,  # Tier 1 always "succeeds" as a template
        )

    except Exception as e:
        # Tier 1 MUST NOT FAIL - return minimal template on any error
        return _fallback_scaffold(finding, str(e))


def _fallback_scaffold(finding: Finding, error: str) -> TestScaffold:
    """Generate minimal fallback scaffold when main generation fails."""
    finding_id = getattr(finding, "id", "UNKNOWN") or "UNKNOWN"
    content = f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

// VKG TEST SCAFFOLD - FALLBACK
// Generated due to error: {error}
// Finding ID: {finding_id}

// TODO: Implement test manually
contract Test_Fallback {{
    function test_vulnerability() public {{
        // TODO: Implement test
        revert("Not implemented");
    }}
}}
'''
    return TestScaffold(
        finding_id=finding_id,
        tier=1,
        content=content,
        filename="Test_Fallback.t.sol",
        confidence=0.5,
    )


def _make_safe_identifier(s: str) -> str:
    """Convert string to safe Solidity identifier."""
    if not s:
        return "Unknown"

    # Replace non-alphanumeric with underscore
    safe = "".join(c if c.isalnum() else "_" for c in s)

    # Remove consecutive underscores
    while "__" in safe:
        safe = safe.replace("__", "_")

    # Remove leading/trailing underscores
    safe = safe.strip("_")

    # Ensure doesn't start with number
    if safe and safe[0].isdigit():
        safe = "X" + safe

    return safe or "Unknown"


def _extract_contract_name(location: str) -> str:
    """Extract contract name from location string."""
    if not location:
        return "TargetContract"

    # Location might be "Contract.sol:functionName:line" or just a path
    path_part = location.split(":")[0] if ":" in location else location

    # Get filename without extension
    try:
        name = Path(path_part).stem
        return name if name else "TargetContract"
    except Exception:
        return "TargetContract"


def _extract_category(finding: Finding) -> str:
    """Extract vulnerability category from finding."""
    # Try to infer from title or description
    title = (finding.title or "").lower()
    desc = (finding.description or "").lower()
    combined = f"{title} {desc}"

    categories = [
        ("reentrancy", ["reentran", "re-entran", "callback"]),
        ("access_control", ["access", "permission", "owner", "admin", "auth", "unauthorized"]),
        ("oracle", ["oracle", "price", "chainlink", "twap"]),
        ("mev", ["mev", "sandwich", "frontrun", "backrun", "slippage"]),
        ("dos", ["dos", "denial", "unbounded", "loop", "gas"]),
        ("overflow", ["overflow", "underflow", "arithmetic"]),
        ("signature", ["signature", "ecrecover", "eip712", "replay"]),
    ]

    for cat_name, keywords in categories:
        for keyword in keywords:
            if keyword in combined:
                return cat_name

    return "unknown"


def _indent_text(text: str, prefix: str = "    // ") -> str:
    """Indent multi-line text for comments."""
    if not text:
        return prefix + "No information provided"

    lines = text.strip().split("\n")
    return f"\n{prefix}".join(lines)


def _generate_attack_steps(category: str) -> str:
    """Generate attack step comments based on category."""
    category = category.lower()

    attack_patterns = {
        "reentrancy": '''        // Attack Pattern: Reentrancy
        // 1. Attacker deploys contract with malicious receive()/fallback()
        // 2. Attacker calls vulnerable withdraw() function
        // 3. Before state is updated, attacker re-enters via callback
        // 4. Attacker drains funds by repeated re-entry''',

        "access_control": '''        // Attack Pattern: Missing Access Control
        // 1. Identify privileged function without access check
        // 2. Call function as non-privileged user
        // 3. Verify state was modified (should have been rejected)''',

        "oracle": '''        // Attack Pattern: Oracle Manipulation
        // 1. Manipulate oracle price (flash loan, sandwich, etc.)
        // 2. Call function that relies on manipulated price
        // 3. Profit from price discrepancy''',

        "mev": '''        // Attack Pattern: MEV Vulnerability
        // 1. Monitor mempool for target transaction
        // 2. Front-run with price manipulation
        // 3. Execute original transaction at worse price
        // 4. Back-run to extract profit''',

        "dos": '''        // Attack Pattern: Denial of Service
        // 1. Identify resource consumption vector (loops, storage, external calls)
        // 2. Trigger resource exhaustion
        // 3. Verify function becomes unusable''',

        "overflow": '''        // Attack Pattern: Arithmetic Overflow/Underflow
        // 1. Identify arithmetic operation without SafeMath (pre-0.8.0)
        // 2. Provide inputs that cause overflow/underflow
        // 3. Verify unexpected state change''',

        "signature": '''        // Attack Pattern: Signature Vulnerability
        // 1. Obtain or forge a valid signature
        // 2. Replay signature on different chain/contract
        // 3. Or: Submit malformed signature that passes ecrecover''',
    }

    # Find matching pattern or use generic
    for key, pattern in attack_patterns.items():
        if key in category:
            return pattern

    return '''        // Attack Pattern: Generic
        // 1. Identify preconditions for vulnerability
        // 2. Execute attack transaction
        // 3. Verify vulnerability was exploited'''


# =============================================================================
# TIER 2 GENERATOR - Smart template with resolved imports
# =============================================================================

TIER2_TEMPLATE = '''// SPDX-License-Identifier: MIT
pragma solidity {pragma_version};

// =============================================================================
// VKG TEST SCAFFOLD - TIER 2 (Smart Template)
// Generated: {timestamp}
// Finding: {finding_id}
// Compile Confidence: {confidence:.0%}
// =============================================================================
//
// This template attempts to resolve imports and match pragma versions.
// Expected compile rate: 30-40% (realistic, not aspirational)
//
// If this doesn't compile, check:
// 1. Import paths are correct for your project structure
// 2. Pragma version matches your contracts
// 3. forge-std is installed (forge install foundry-rs/forge-std)
//
// =============================================================================

{imports}

/**
 * @title {test_contract_name}
 * @notice Test for: {finding_title}
 * @dev Tier 2: Smart template with resolved imports
 */
contract {test_contract_name} is Test {{
    // =========================================================================
    // VULNERABILITY SUMMARY
    // =========================================================================
    // ID: {finding_id}
    // Severity: {severity}
    // Location: {location}
    //
    // Description:
    // {description}
    // =========================================================================

    {target_contract_type} public target;

    function setUp() public {{
        // Deploy target contract
        // TODO: Adjust constructor arguments as needed
        target = new {target_contract_type}();

        // TODO: Set up initial state
        // vm.deal(address(this), 10 ether);
        // target.initialize(...);
    }}

    function test_{finding_id_safe}_{category_safe}() public {{
{attack_steps}

        // TODO: Record initial state
        // uint256 initialBalance = address(target).balance;

        // TODO: Execute attack
        // target.vulnerableFunction();

        // TODO: Assert vulnerability
        // assertGt(address(this).balance, 0, "Should have extracted funds");

        revert("Test not implemented - complete TODO sections");
    }}

    // Callback for reentrancy tests
    receive() external payable {{
        // TODO: Implement callback if testing reentrancy
    }}
}}
'''


def generate_tier2_scaffold(
    finding: Finding,
    project_config: Optional[ProjectConfig] = None,
    source_pragma: Optional[str] = None,
) -> TestScaffold:
    """
    Generate Tier 2 test scaffold with smart import resolution.

    Attempts to:
    - Resolve import paths based on project structure
    - Match pragma version to source contract
    - Include forge-std/Test.sol import
    - Provide basic setUp() structure

    Expected compile rate: 30-40%

    Args:
        finding: The finding to generate test for
        project_config: Optional project configuration for import resolution
        source_pragma: Optional pragma from source contract

    Returns:
        TestScaffold with smart template content
    """
    try:
        # Extract finding info
        finding_id = finding.id or "UNKNOWN"
        finding_id_safe = _make_safe_identifier(finding_id)
        category = _extract_category(finding)
        category_safe = _make_safe_identifier(category)
        test_contract_name = f"Test_{finding_id_safe}_{category_safe}"

        # Location and contract info
        location = finding.location or "unknown"
        target_contract_type = _extract_contract_name(location)

        # Determine pragma version
        pragma_version = suggest_test_pragma(source_pragma)

        # Build imports
        imports, confidence = _build_tier2_imports(
            project_config,
            location,
            target_contract_type,
        )

        # Generate attack steps
        attack_steps = _generate_attack_steps(category)

        # Generate content
        content = TIER2_TEMPLATE.format(
            timestamp=datetime.now().isoformat(),
            finding_id=finding_id,
            finding_id_safe=finding_id_safe,
            finding_title=finding.title or "Unknown Vulnerability",
            severity=finding.severity.value if finding.severity else "unknown",
            category=category,
            category_safe=category_safe,
            location=location,
            description=_indent_text(finding.description or "No description"),
            test_contract_name=test_contract_name,
            target_contract_type=target_contract_type,
            pragma_version=pragma_version,
            imports=imports,
            attack_steps=attack_steps,
            confidence=confidence,
        )

        filename = f"{test_contract_name}.t.sol"

        return TestScaffold(
            finding_id=finding_id,
            tier=2,
            content=content,
            filename=filename,
            confidence=confidence,
        )

    except Exception as e:
        # Fall back to Tier 1 on any error
        scaffold = generate_tier1_scaffold(finding)
        scaffold.compilation_error = f"Tier 2 failed: {e}, fell back to Tier 1"
        return scaffold


def _build_tier2_imports(
    project_config: Optional[ProjectConfig],
    location: str,
    target_contract_type: str,
) -> tuple[str, float]:
    """
    Build import statements for Tier 2.

    Returns:
        Tuple of (imports string, confidence score)
    """
    imports = []
    confidence = 0.4  # Base confidence for Tier 2

    # Always try to add forge-std
    if project_config:
        resolver = ImportResolver(project_config)
        forge_import = resolver.suggest_forge_std_import()
        imports.append(forge_import)

        # If forge-std resolves cleanly, boost confidence
        if not forge_import.startswith("//"):
            confidence += 0.1

        # Try to resolve target contract import
        if location and location != "unknown":
            # Extract just the file path from location
            file_path = location.split(":")[0] if ":" in location else location

            if file_path:
                # Try to build import path
                try:
                    contract_path = Path(file_path)
                    import_stmt = resolver.resolve_contract_import(contract_path)
                    imports.append(import_stmt)

                    # Boost confidence if resolved without TODO
                    if "TODO" not in import_stmt:
                        confidence += 0.1
                except Exception:
                    imports.append(f'// TODO: Import target contract\n// import "{file_path}";')
            else:
                imports.append(f"// TODO: Import {target_contract_type}")
        else:
            imports.append(f"// TODO: Import {target_contract_type}")

    else:
        # No project config - use defaults
        imports.append('import "forge-std/Test.sol";')
        imports.append(f"// TODO: Import {target_contract_type}")
        confidence = 0.25  # Lower confidence without project config

    return "\n".join(imports), min(confidence, 0.6)  # Cap at 60%


# =============================================================================
# BATCH GENERATION
# =============================================================================

def generate_scaffolds(
    findings: List[Finding],
    tier: TestTier = TestTier.TIER_1_TEMPLATE,
    project_config: Optional[ProjectConfig] = None,
) -> List[TestScaffold]:
    """
    Generate test scaffolds for multiple findings.

    Args:
        findings: List of findings to generate tests for
        tier: Target tier level
        project_config: Optional project configuration

    Returns:
        List of TestScaffold instances
    """
    scaffolds = []

    for finding in findings:
        if tier == TestTier.TIER_1_TEMPLATE:
            scaffold = generate_tier1_scaffold(finding)
        elif tier == TestTier.TIER_2_SMART:
            scaffold = generate_tier2_scaffold(finding, project_config)
        else:
            # Tier 3 not implemented - fall back to Tier 2
            scaffold = generate_tier2_scaffold(finding, project_config)
            scaffold.tier = 3
            scaffold.confidence *= 0.25  # Much lower confidence

        scaffolds.append(scaffold)

    return scaffolds


def write_scaffold_to_file(
    scaffold: TestScaffold,
    output_dir: Path,
) -> Path:
    """
    Write scaffold to file in output directory.

    Args:
        scaffold: The scaffold to write
        output_dir: Directory to write to

    Returns:
        Path to written file
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / scaffold.filename
    output_path.write_text(scaffold.content)
    return output_path
