"""Alias maps for NL-to-property normalization."""

from __future__ import annotations

PROPERTY_ALIASES = {
    "auth gate": "has_access_gate",
    "access gate": "has_access_gate",
    "access control": "has_access_gate",
    "reentrancy guard": "has_reentrancy_guard",
    "reentrancy": "has_reentrancy_guard",
    "delegate call": "uses_delegatecall",
    "delegatecall": "uses_delegatecall",
    "tx origin": "uses_tx_origin",
    "tx.origin": "uses_tx_origin",
    "msg sender": "uses_msg_sender",
    "msg.sender": "uses_msg_sender",
    "external call": "has_external_calls",
    "external calls": "has_external_calls",
    "has external call": "has_external_calls",
    "has external calls": "has_external_calls",
    "state write": "writes_state",
    "state writes": "writes_state",
    "writes state": "writes_state",
    "has low level call": "has_low_level_calls",
    "has low level calls": "has_low_level_calls",
    "checks return value": "checks_low_level_call_success",
    "calls erc20 transfer": "uses_erc20_transfer",
    "uses safe erc20": "uses_safe_erc20",
    "interacts with token type": "token_callback_surface",
    "writes state after token interaction": "state_write_after_external_call",
    "reads state modified by nonreentrant": "read_only_reentrancy_surface",
    "likely called by external protocol": "read_only_reentrancy_surface",
    "has functions sharing state": "has_functions_sharing_state",
    "slippage check": "has_slippage_check",
    "deadline check": "has_deadline_check",
    "upgrade function": "is_upgrade_function",
    "initializer": "is_initializer_function",
    "calls external contract": "calls_external_contract",
    "calls external contracts": "calls_external_contract",
    "callback chain": "callback_chain_surface",
    "callback entrypoint": "callback_entrypoint_surface",
}

NODE_TYPE_ALIASES = {
    "contracts": "Contract",
    "contract": "Contract",
    "functions": "Function",
    "function": "Function",
    "state variables": "StateVariable",
    "state variable": "StateVariable",
    "events": "Event",
    "event": "Event",
    "modifiers": "Modifier",
    "modifier": "Modifier",
}

EDGE_ALIASES = {
    "external calls": "CALLS_EXTERNAL",
    "external call": "CALLS_EXTERNAL",
    "calls contract": "CALLS_CONTRACT",
    "call contract": "CALLS_CONTRACT",
    "contract calls": "CALLS_CONTRACT",
    "calls external contract": "CALLS_CONTRACT",
    "external contract calls": "CALLS_CONTRACT",
    "internal calls": "CALLS_INTERNAL",
    "internal call": "CALLS_INTERNAL",
    "reads": "READS_STATE",
    "read": "READS_STATE",
    "writes": "WRITES_STATE",
    "write": "WRITES_STATE",
    "uses modifier": "USES_MODIFIER",
    "inherits": "INHERITS",
    "inheritance": "INHERITS",
}
